### ISSUE TITLE
How it works your playwright configuration.

### ISSUE THREAD

**Issue by Afsoon** [edmundhung/remix-cloudflare-template#13]
I have a question about your playwright configuration. 

I see you are using Vite to create a server, I have done something similar but with Express and using the code emitted by Remix's Esbuild. 

My two questions are:

- If I'm not mistaken, this configuration doesn't require a previous `npm run build` because we are using Vite directly.
- Does the actual MSW configuration allow you the following situation?

Test A -> Mock Handler `A with response X, B with response Y, C with response Z`
Test B -> Mock Handler `A with response H, B with response J`

**Comment by edmundhung** [comment]
> If I'm not mistaken, this configuration doesn't require a previous npm run build because we are using Vite directly.

Correct. We are running the vite dev server for tests. Ideally it would be the wrangler dev server with workerd but their API is kinda limited at the moment.

> Does the actual MSW configuration allow you the following situation?

I think you will need the new [server boundary](https://mswjs.io/blog/introducing-server-boundary) just introduced in msw v2.2. As I explained in the playwright fixture setup, the idea of running both the vite dev server and msw there is mainly to ensure them running in the same process to enable server side mocking.

**Comment by Afsoon** [comment]
Thank you for your fast response @edmundhung !
